version: '2'

run:
   enable-cache: true

linters:
   default: none
   enable:
      - goconst
      - gocritic
      - govet
      - unused
      - cyclop

   settings:
      goconst:
         find-duplicates: true
      gocritic:
         disable:
            - parallelize
            - nesting
            - hugeParam
            - hugeStruct
            - nestParam
            - prealloc
      govet:
         shadow: true
         tests: true
      unused:
         check-exported: true
         check-packages: true
         check-generated: true
         tests: true
         allow-unused-type-export: true
      cyclop:
         average-strictness: 12

   exclusions:
      paths:
         - vendor
         - bundle
         - hack
         - img
         - third_party$
         - builtin$
         - examples$

      rules:
         - text: testpackage
           path: _test\.go

      generated: lax
      presets:
         - comments
         - common-false-positives
         - legacy
         - std-error-handling

formatters:
   enable:
      - gci

   settings:
      gci:
         max-len: 120
         line-length: 120

   exclusions:
      generated: lax
      paths:
         - third_party$
         - builtin$
         - examples$
